targetInstance: ${TEST_URL:https://rd-user-profile-api-pr-107.service.core-compute-preview.internal}
spring.flyway.enabled: false
idamUrl: ${IDAM_URL_TO_TEST:https://idam-api.aat.platform.hmcts.net}

idam.api.url: ${IDAM_URL_TO_TEST:https://idam-api.aat.platform.hmcts.net}

generated.user.email.pattern: ${GENERATED_USER_EMAIL_PATTERN:freg-test-user-%s@feemail.com}
test.url: ${TEST_URL:http://rd-user-profile-api-aat.service.core-compute-aat.internal}
test.user.password: ${TEST_USER_PASSWORD:Hmcts123}

s2s.auth.secret: ${S2S_SECRET:OLMEJQA7UHU6EZKG}
s2s.auth.url: ${S2S_URL_TO_TEST:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

idam.auth.tokenAuth: ${IDAM_TOKEN_ATUH:cmQtcHJvZmVzc2lvbmFsLWFwaTpjYzVmMmE2LTk2OTAtMTFlOS1iYzQyLTUyNmFmNzc2NGY2NA==}
idam.auth.redirectUrl: ${IDAM_REDIRECT_URL:https://rd-professional-api-aat.service.core-compute-aat.internal/oauth2redirect}
idam.auth.clientId: rd-professional-api
idam:auth:clientSecret: cc5f2a6-9690-11e9-bc42-526af7764f64
## Secure roles configuration 1
exui.role.hmcts-admin: prd-admin
exui.role.pui-user-manager: pui-user-manager
exui.role.pui-organisation-manager: pui-organisation-manager
exui.role.pui-finance-manager: pui-finance-manager
exui.role.pui-case-manager: pui-case-manager