targetInstance: ${TEST_URL:http://rd-user-profile-api-demo.service.core-compute-demo.internal}
spring.flyway.enabled: false
idamUrl: ${IDAM_URL_TO_TEST:https://idam-api.demo.platform.hmcts.net}

idam.api.url: ${IDAM_URL_TO_TEST:https://idam-api.demo.platform.hmcts.net}

generated.user.email.pattern: ${GENERATED_USER_EMAIL_PATTERN:freg-test-user-%s@feemail.com}
test.url: ${TEST_URL:http://rd-user-profile-api-demo.service.core-compute-ithc.internal}
test.user.password: ${TEST_USER_PASSWORD:Hmcts123}

s2s.auth.secret: ${S2S_SECRET:EIN42QX5MANYZNDD}
s2s.auth.url: ${S2S_URL_TO_TEST:http://rpe-service-auth-provider-demo.service.core-compute-demo.internal}

idam.auth.tokenAuth: ${IDAM_TOKEN_ATUH:cmQtcHJvZmVzc2lvbmFsLWFwaTpjYzVmMmE2LTk2OTAtMTFlOS1iYzQyLTUyNmFmNzc2NGY2NA==}
idam.auth.redirectUrl: ${IDAM_REDIRECT_URL:https://rd-professional-api-demo.service.core-compute-demo.internal/oauth2redirect}
idam.auth.clientId: rd-professional-api