spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbuserprofile
    username: ${POSTGRES_USERNAME:dbuserprofile}
    password: ${POSTGRES_PASSWORD:dbuserprofile}

security:

  authorisedServices:
    - "it"

auth.idam.client.baseUrl: ${IDAM_URL:http://127.0.0.1:5000}
auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:8099}