apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rd-user-profile-api
name: rd-user-profile-api
home: https://github.com/hmcts/rd-user-profile-api
version: 0.0.32
maintainers:
  - name: Reference Data Team
dependencies:
  - name: java
    version: 5.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
